version: '3'

services:
    shard1:
        image: postgres:13.4
        command: [ "postgres", "-c", "log_statement=all" ]
        environment:
            - POSTGRES_USER=user1
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=db1
        ports:
            - "6432:5432"

    shard2:
        image: postgres:13.4
        command: [ "postgres", "-c", "log_statement=all" ]
        environment:
            - POSTGRES_USER=user1
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=db1
        ports:
            - "7432:5432"
    
    router:
        build:
            dockerfile: ./docker/router/Dockerfile
            context: .
        ports:
            - "8432:6432"
    
    client:
        build:
            dockerfile: ./docker/tests/Dockerfile
            context: .
